baseURL = "https://20h.dev"
languageCode = "ko"
DefaultContentLanguage = "ko"
title = "journey"

# theme as hugo module
#theme = "github.com/lxndrblz/anatole"
# theme as git submodule
theme = "anatole"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
googleAnalytics = "G-3YKR0LLEP9"

# Syntax highlighting
pygmentsUseClasses = false
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Localized dates requires Hugo version 0.87.0
localizedDates = false

[markup]
    [markup.highlight]
        style = "dracula"
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80

[params.giscus]
  repo = "lee20h/blog"
  repoID = "R_kgDOKNxRtA"
  category = "General"
  categoryID = "DIC_kwDOKNxRtM4CZErD"
  data-mapping="pathname"
  data-strict="0"
  data-reactions-enabled="1"
  data-emit-metadata="0"
  data-input-position="bottom"
  data-theme="light_high_contrast"
  data-lang="ko"
  crossorigin="anonymous"

[sitemap]
  changefreq = "always"
  priority = 1.0
  filename = "sitemap.xml"

[params]
customSCSS = ["scss/custom.scss"]